### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Moto_HMI_UIContent)
add_subdirectory(Moto_HMI_UI)
add_subdirectory(Generated)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Moto_HMI_UIContentplugin
    Moto_HMI_UIplugin
    Generated_QtQuick3D_Bike_uv_from_substance_v002plugin)